using MassTransit.Testing;
using MassTransit;
using Sample.Components.StateMachines;
using System.Threading.Tasks;
using Xunit;
using Sample.Contracts.Events;
using FluentAssertions;
using Automatonymous.Graphing;
using System;
using Automatonymous.Visualizer;
using System.IO;

namespace Sample.UnitTests.StateMachines
{
    public class OrderStateMachineTests
    {
        [Fact]
        public async Task OrderStateMachine_CorrectPayload_CreatesStateInstance()
        {
            // Arrange
            using var harness = new InMemoryTestHarness();
            var orderStateMachine = new OrderStateMachine();
            var saga = harness.StateMachineSaga<OrderState, OrderStateMachine>(orderStateMachine);
            var orderId = NewId.NextGuid();

            await harness.Start();

            // Act
            await harness.Bus.Publish<OrderSubmitted>(new
            {
                OrderId = orderId,
                InVar.Timestamp,
                CustomerNumber = "12345"
            });
            var instanceId = await saga.Exists(orderId, x => x.Submitted);

            // Assert
            saga.Created.Contains(orderId).Should().NotBeNull();
            instanceId.Should().HaveValue();
            saga.Sagas.Contains(instanceId.Value).CustomerNumber.Should().BeEquivalentTo("12345");
        }

        [Fact]
        public async Task OrderStateMachine_CustomerAccountClosed_OrderStateIsChangedToCancelled()
        {
            // Arrange
            using var harness = new InMemoryTestHarness();
            var orderStateMachine = new OrderStateMachine();
            var saga = harness.StateMachineSaga<OrderState, OrderStateMachine>(orderStateMachine);
            var orderId = NewId.NextGuid();

            await harness.Start();

            // Act
            await harness.Bus.Publish<OrderSubmitted>(new
            {
                OrderId = orderId,
                InVar.Timestamp,
                CustomerNumber = "12345"
            });
            var instanceId = await saga.Exists(orderId, x => x.Submitted);

            await harness.Bus.Publish<CustomerAccountClosed>(new
            {
                CustomerId = InVar.Id,
                CustomerNumber = "12345"
            });
            await saga.Exists(orderId, x => x.Cancelled);

            // Assert
            saga.Created.Contains(orderId).Should().NotBeNull();
            instanceId.Should().HaveValue();
            saga.Sagas.Contains(instanceId.Value).CustomerNumber.Should().BeEquivalentTo("12345");
        }

        [Fact]
        public async Task OrderStateMachine_OrderIsAccepted_OrderStateIsChangedToAccept()
        {
            // Arrange
            using var harness = new InMemoryTestHarness();
            var orderStateMachine = new OrderStateMachine();
            var saga = harness.StateMachineSaga<OrderState, OrderStateMachine>(orderStateMachine);
            var orderId = NewId.NextGuid();

            await harness.Start();

            // Act
            await harness.Bus.Publish<OrderSubmitted>(new
            {
                OrderId = orderId,
                InVar.Timestamp,
                CustomerNumber = "12345"
            });
            var instanceId = await saga.Exists(orderId, x => x.Submitted);

            await harness.Bus.Publish<OrderAccepted>(new
            {
                CustomerId = InVar.Id,
                CustomerNumber = "12345"
            });
            await saga.Exists(orderId, x => x.Accepted);

            // Assert
            saga.Created.Contains(orderId).Should().NotBeNull();
            instanceId.Should().HaveValue();
            saga.Sagas.Contains(instanceId.Value).CustomerNumber.Should().BeEquivalentTo("12345");
        }

        /// <summary>
        /// Generates .dot file with State Machine diagram.
        /// </summary>
        /// <remarks>
        /// Copy contents of file generated by this and paste them on the page: <see href="https://dreampuf.github.io/GraphvizOnline/"/>
        /// It will give you visualization of OrderStateMachine
        /// </remarks>
        [Fact]
        public async Task GenerateStateMachineGraph()
        {
            var orderStateMachine = new OrderStateMachine();

            var graph = orderStateMachine.GetGraph();

            var generator = new StateMachineGraphvizGenerator(graph);

            string dots = generator.CreateDotFile();
            var filePath = Path.Combine(Environment.CurrentDirectory, "OrderStateMachine_graph.dot");
            await File.WriteAllTextAsync(filePath, dots);
        }
    }
}